name: Build Specific TensorFlowLiteC Version

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to build'
        required: true
      
permissions:
  contents: write
  
jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-tags: true
        
      - name: Check if Tag Exists and Build
        run: |
          if git rev-parse "refs/tags/${{ github.event.inputs.release_version }}" >/dev/null 2>&1; then
            echo "Tag exists for ${{ github.event.inputs.release_version }}. Exiting early."
            exit 0
          else
            echo "Tag for ${{ github.event.inputs.release_version }} does not exist. Proceeding with build..."
          fi
        
      - name: Prepare XCFramework Directory
        run: |
          cd ${{ github.workspace }}
          mkdir -p TensorFlowLiteC/Device
          mkdir -p TensorFlowLiteC/Simulator
          mkdir -p TensorFlowLiteCCoreML/Device
          mkdir -p TensorFlowLiteCCoreML/Simulator
          
      - name: Build TensorFlowLiteC/TensorFlowLiteCCoreML on Simulator
        run: |
          cd ${{ github.workspace }}/App
          
          cp -f Podfile.version Podfile
          sed -i '' -e "s|{{VERSION}}|${{ github.event.inputs.release_version }}|g" Podfile
          
          pod install

          cp -R Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.xcframework/ios-arm64_x86_64-simulator/TensorFlowLiteC.framework ${{ github.workspace }}/TensorFlowLiteC/Simulator
          cp ${{ github.workspace }}/Info-TensorFlowLiteC.plist ${{ github.workspace }}/TensorFlowLiteC/Simulator/TensorFlowLiteC.framework/Info.plist
          
          cp -R Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteCCoreML.xcframework/ios-arm64_x86_64-simulator/TensorFlowLiteCCoreML.framework ${{ github.workspace }}/TensorFlowLiteCCoreML/Simulator
          cp ${{ github.workspace }}/Info-TensorFlowLiteCCoreML.plist ${{ github.workspace }}/TensorFlowLiteCCoreML/Simulator/TensorFlowLiteCCoreML.framework/Info.plist
          
      - name: Clone TensorFlow Repository
        uses: actions/checkout@v4
        with:
          repository: 'tensorflow/tensorflow'
          path: '${{ github.workspace }}/tensorflow'
          fetch-tags: true
          ref: 'v${{ github.event.inputs.release_version }}'
          
      - name: Setup Bazel Version
        run: |
          echo "USE_BAZEL_VERSION=$(head -n 1 ${{ github.workspace }}/tensorflow/.bazelversion)" >> $GITHUB_ENV
          
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: '${{ github.workflow }}'
          repository-cache: true
          cache-version: 5
          
      - name: Install expect
        run: brew install expect
        
      - name: Configure TensorFlow
        run: |
          cd ${{ github.workspace }}/tensorflow
          expect -c '
            spawn ./configure
            expect "Please specify the location of python*"
            send "\r"
            expect "Please input the desired Python library path to use*"
            send "\r"
            expect "Do you wish to build TensorFlow with ROCm support*"
            send "N\r"
            expect "Do you wish to build TensorFlow with CUDA support*"
            send "N\r"
            expect "Please specify optimization flags to use during compilation*"
            send "\r"
            expect "Would you like to interactively configure ./WORKSPACE for Android builds?*"
            send "N\r"
            expect "Do you wish to build TensorFlow with iOS support?*"
            send "y\r"
            interact
          '
          
      - name: Build TensorFlowLiteC on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          build_output=$(bazel build --config=ios --ios_multi_cpus="arm64" -c opt --cxxopt=--std=c++17 //tensorflow/lite/ios:TensorFlowLiteC_static_framework 2>&1 >/dev/null)
          zip_file=$(echo "$build_output" | grep -o '[^ ]*\_framework.zip')
          unzip -o $zip_file -d ${{ github.workspace }}/TensorFlowLiteC/Device
          cp ${{ github.workspace }}/Info-TensorFlowLiteC.plist ${{ github.workspace }}/TensorFlowLiteC/Device/TensorFlowLiteC.framework/Info.plist
          
      - name: Build TensorFlowLiteCCoreML on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          git apply ../build_coreml_statically.patch
          build_output=$(bazel build --config=ios --ios_multi_cpus="arm64" -c opt --cxxopt=--std=c++17 //tensorflow/lite/ios:TensorFlowLiteCCoreML_framework 2>&1 >/dev/null)
          zip_file=$(echo "$build_output" | grep -o '[^ ]*\_framework.zip')
          unzip -o $zip_file -d ${{ github.workspace }}/TensorFlowLiteCCoreML/Device
          cp ${{ github.workspace }}/Info-TensorFlowLiteCCoreML.plist ${{ github.workspace }}/TensorFlowLiteCCoreML/Device/TensorFlowLiteCCoreML.framework/Info.plist
          
      - name: Create XCFramework
        run: |
          cd ${{ github.workspace }}/TensorFlowLiteC
          
          xcodebuild -create-xcframework \
            -framework ./Device/TensorFlowLiteC.framework \
            -framework ./Simulator/TensorFlowLiteC.framework \
            -output ${{ github.workspace }}/TensorFlowLiteC.xcframework
          
          cd ${{ github.workspace }}/TensorFlowLiteCCoreML
          
          xcodebuild -create-xcframework \
            -framework ./Device/TensorFlowLiteCCoreML.framework \
            -framework ./Simulator/TensorFlowLiteCCoreML.framework \
            -output ${{ github.workspace }}/TensorFlowLiteCCoreML.xcframework

          cd ${{ github.workspace }}

          zip -r TensorFlowLiteC.xcframework.zip TensorFlowLiteC.xcframework
          zip -r TensorFlowLiteCCoreML.xcframework.zip TensorFlowLiteCCoreML.xcframework

          touch Package.swift

          echo "TENSOR_FLOW_LITE_C_CHECKSUM=$(xcrun swift package compute-checksum TensorFlowLiteC.xcframework.zip)" >> $GITHUB_ENV
          echo "TENSOR_FLOW_LITE_C_CORE_ML_CHECKSUM=$(xcrun swift package compute-checksum TensorFlowLiteCCoreML.xcframework.zip)" >> $GITHUB_ENV
          
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: '*.zip'
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: true
          
      - name: Get API URL
        env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          TENSOR_FLOW_LITE_C_API_URL=$(gh release view 2.14.0 --json assets -q '.assets[] | select (.name == "TensorFlowLiteC.xcframework.zip").apiUrl')
          TENSOR_FLOW_LITE_C_CORE_ML_API_URL=$(gh release view 2.14.0 --json assets -q '.assets[] | select (.name == "TensorFlowLiteCCoreML.xcframework.zip").apiUrl')
          echo "TENSOR_FLOW_LITE_C_API_URL=$TENSOR_FLOW_LITE_C_API_URL.zip" >> $GITHUB_ENV
          echo "TENSOR_FLOW_LITE_C_CORE_ML_API_URL=$TENSOR_FLOW_LITE_C_CORE_ML_API_URL.zip" >> $GITHUB_ENV
          
      - name: Update Package.swift
        run: |
          cp -f Package.swift.in Package.swift
          sed -i '' -e "s|{{TENSOR_FLOW_LITE_C_API_URL}}|${{ env.TENSOR_FLOW_LITE_C_API_URL }}|g" Package.swift
          sed -i '' -e "s|{{TENSOR_FLOW_LITE_C_CHECKSUM}}|${{ env.TENSOR_FLOW_LITE_C_CHECKSUM }}|g" Package.swift
          sed -i '' -e "s|{{TENSOR_FLOW_LITE_C_CORE_ML_API_URL}}|${{ env.TENSOR_FLOW_LITE_C_CORE_ML_API_URL }}|g" Package.swift
          sed -i '' -e "s|{{TENSOR_FLOW_LITE_C_CORE_ML_CHECKSUM}}|${{ env.TENSOR_FLOW_LITE_C_CORE_ML_CHECKSUM }}|g" Package.swift
          git add Package.swift
          git commit -m "Update Package.swift"
          git push
          git tag -m "Update release commit" -f -a ${{ env.RELEASE_VERSION }} $(git rev-parse origin/main)
          git push -f origin refs/tags/${{ env.RELEASE_VERSION }}
