name: Build TensorFlowLiteC

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone TensorFlow Repository
        run: git clone https://github.com/tensorflow/tensorflow ${{ github.workspace }}/tensorflow

      - name: Parse .bazelversion
        run: |
          BAZEL_VERSION=$(head -n 1 ${{ github.workspace }}/tensorflow/.bazelversion)
          echo "Bazel version: $BAZEL_VERSION" > bazel_version.txt

      - name: Install Bazel
        run: |
          brew install bazel@$(cat bazel_version.txt)
          brew link --overwrite bazel@$(cat bazel_version.txt)

      - name: Build TensorFlowLiteC on Simulator
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls

      - name: Build TensorFlowLiteC on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls
