name: Build TensorFlowLiteC

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: macos-latest

    steps:
      - name: Setup Bazel Version
        run: echo "USE_BAZEL_VERSION=6.5.0" >> $GITHUB_ENV

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: ${{ github.workflow }}-2
          disk-cache: ${{ github.workflow }}-2
          repository-cache: ${{ github.workflow }}-2

      - name: Which Bazel
        run: |
          echo $USE_BAZEL_VERSION
          which bazel && bazel --version
#      - name: Checkout Repository
#        uses: actions/checkout@v2
        
#      - name: Clone TensorFlow Repository
#        run: which brew && which bazel && bazel --version
        
#      - name: Set Bazel version
#        run: |
#          cd ${{ github.workspace }}/tensorflow
#          USE_BAZEL_VERSION=$(head -n 1 ${{ github.workspace }}/tensorflow/.bazelversion)
#          echo Installing $USE_BAZEL_VERSION
#          
#      - name: Install Bazel
#        uses: bazel-contrib/setup-bazel@0.8.1
#        with:
#            bazelisk-cache: true
#            disk-cache: ${{ github.workflow }}-1
#            repository-cache: true
#
#      - name: Build TensorFlowLiteC on Simulator
#        run: |
#          bazel --version
#
#      - name: Build TensorFlowLiteC on Device
#        run: |
#          bazel --version
