name: Build TensorFlowLite

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone TensorFlow Repository
        run: git clone https://github.com/tensorflow/tensorflow ${{ github.workspace }}/tensorflow

      - name: Build TensorFlowLite on Simulator
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls

      - name: Build TensorFlowLite on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls
