name: Build TensorFlowLiteC

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Clone TensorFlow Repository
        run: git clone https://github.com/tensorflow/tensorflow ${{ github.workspace }}/tensorflow

      - name: Setup Bazel Version
        run: |
          echo "USE_BAZEL_VERSION=$(head -n 1 ${{ github.workspace }}/tensorflow/.bazelversion)" >> $GITHUB_ENV

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-version: 5
          
      - name: Install expect
        run: brew install expect
        
      - name: Build TensorFlowLiteC on Simulator
        run: |
          cd ${{ github.workspace }}/tensorflow
          spawn ./configure
          expect "Do you wish to build TensorFlow with iOS support? [y/N]:"
          send "y\r"
          bazel --version

      - name: Build TensorFlowLiteC on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          spawn ./configure
          expect "Do you wish to build TensorFlow with iOS support? [y/N]:"
          send "y\r"
          bazel build --config=ios --ios_multi_cpus="arm64" -c opt --cxxopt=--std=c++17 //tensorflow/lite/ios:TensorFlowLiteC_static_framework
