name: Build TensorFlowLiteC

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Clone TensorFlow Repository
        run: git clone https://github.com/tensorflow/tensorflow ${{ github.workspace }}/tensorflow
        
      - name: Navigate to cloned repository
        run: cd ${{ github.workspace }}/tensorflow

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
            bazelisk-cache: true
            disk-cache: ${{ github.workflow }}
            repository-cache: true
        run: |
          bazel --version

      - name: Build TensorFlowLiteC on Simulator
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls

      - name: Build TensorFlowLiteC on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls
