name: Build TensorFlowLiteC

on:
  push:
    branches:
      - main

jobs:
  clone_and_build:
    name: Clone TensorFlow and Build TensorFlowLiteC / TensorFlowLiteCCoreML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone TensorFlow Repository
        run: git clone https://github.com/tensorflow/tensorflow ${{ github.workspace }}/tensorflow

      - name: Parse .bazelversion
        run: |
          BAZEL_VERSION=$(head -n 1 ${{ github.workspace }}/tensorflow/.bazelversion)
          echo "Bazel version: $BAZEL_VERSION"
          echo "::set-output name=bazel_version::$BAZEL_VERSION"

      - name: Install Bazel
        uses: ConorMacBride/install-package@v1
        with:
          brew: bazel@${{ steps.parse_bazelversion.outputs.bazel_version }}

      - name: Build TensorFlowLiteC on Simulator
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls

      - name: Build TensorFlowLiteC on Device
        run: |
          cd ${{ github.workspace }}/tensorflow
          ls
